### PR TITLE
moved stuff to develop, bugfixed and rebased 

### PR DESCRIPTION
**Pull request by itmo**

### CODE REVIEW

**Comment by metal3d** [comment]
I'll ckeck in a couple of hours.  Big thanks

**Comment by metal3d** [comment]
Cool but can you please rebase :)
I'm impressed by your contribution, a big Thanks

**Comment by itmo** [comment]
yeah i will see if i have time to rebase it once again.

**Comment by itmo** [comment]
although this doesnt seem to have conficts.

**Comment by itmo** [comment]
as far as i see it should be up to date wrt your master.

**Comment by itmo** [comment]
its up to date, please merge.

**Comment by metal3d** [comment]
What I said is that you've got 46 commits without nice commit message. An interactive rebase to squash commits and using more explicit commit message should help.

I meant you could squash commits in one or two commits.

**Comment by metal3d** [comment]
For exemple
https://github.com/metal3d/bashsimplecurses/pull/17/commits/3008c98f425ef19b3ba399ec147f22d2b9d93e9f
The commit message is "local i" maybe you can squash the whole commit from 638f744 to 22270fd

**Comment by itmo** [comment]
oh you mean a squash, you said "rebase"

**Comment by itmo** [comment]
now its a bit more squashed.

**Comment by metal3d** [comment]
Ok I did a little modification:

- moved all examples in "examples" directory
- change "source" command

So you may need to pull the master from this repos

A real big thanks, I'm impressed by vumeter, progress and so on. But I need to see why "choice" and my "truncate" fixes are not working.

Anyway, the "master" branch is not fully tester, and later I will make a real "dev" branch to be able to merge only fully tested enhancements.

**Pull request merged**
