### PR TITLE
vented some frustrations. bgcolor support plus delay loop and stuff.

### PR DESCRIPTION
**Pull request by itmo**

### CODE REVIEW

**Comment by metal3d** [comment]
Wooow. Let me check that. Nice !

**Comment by itmo** [comment]
the default colors might need some love. currrently they are reset to "default" which doesnt seem to be default for my terminal (too white) i think i will add a reset to the exit

**Comment by itmo** [comment]
disclaimer: i drank a sixpack and watched tv while doing that, so mileage may vary =D works for me.

**Comment by metal3d** [comment]
Well, I've got some problem. Not very important but...
I see an error with $time line 414 (command not found) and a line junction is not bold:

image

Same on you example "choice.sh" that have this problem.

After fixes, can you please rebase your commits before I do a merge ?

Thanks a lot for this PR, very interesssing. And glade to be helped :)

**Comment by metal3d** [comment]
Damned I made conflicts... You need to resolve your branch :\

**Pull request closed without merging**
